perkalian matrix

In [1]:
import numpy as np

A = np.array([[0, 6], [0, 9], [0, 5]])
B = np.array([[4, 5], [0, 6], [1, 1]])
C = np.array([[1, 1], [2, 2], [3, 3]])

kali = A * B * C
print(kali)


[[  0  30]
 [  0 108]
 [  0  15]]


pengurangan matrix

In [2]:
import numpy as np

A = np.array([[0, 6], [0, 9], [0, 5]])
B = np.array([[4, 5], [0, 6], [1, 1]])
C = np.array([[1, 1], [2, 2], [3, 3]])

pengurangan = A - B - C
print(pengurangan)

[[-5  0]
 [-2  1]
 [-4  1]]


transpose matrix

In [4]:
import numpy as np

A = np.array([[0, 6], [0, 9], [0, 5]])
B = np.array([[4, 5], [0, 6], [1, 1]])
C = np.array([[1, 1], [2, 2], [3, 3]])

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)
transpose_C = np.transpose(C)

print(transpose_A)
print(transpose_B)
print(transpose_C)



[[0 0 0]
 [6 9 5]]
[[4 0 1]
 [5 6 1]]
[[1 2 3]
 [1 2 3]]


nilai invers dan determinant

In [8]:
import numpy as np

A = np.array([[0, 6], [0, 9], [0, 5]])
B = np.array([[4, 5], [0, 6], [1, 1]])
C = np.array([[1, 1], [2, 2], [3, 3]])

determinant_A = np.linalg.det(A)
print("Determinant dari matriks A:", determinant_A)

determinant_B = np.linalg.det(B)
print("Determinant dari matriks B:", determinant_B)

determinant_C = np.linalg.det(C)
print("Determinant dari matriks C:", determinant_C)

inverse_A = np.linalg.inv(A)
print("\nInvers matriks A:")
print(inverse_A)

inverse_B = np.linalg.inv(B)
print("\nInvers matriks B:")
print(inverse_B)

inverse_C = np.linalg.inv(C)
print("\nInvers matriks C:")
print(inverse_C)



LinAlgError: Last 2 dimensions of the array must be square